[package]
description = "A fast multiplayer voxel engine."
edition = "2021"
exclude = [
  "client",
  "dist",
  "examples",
  "node_modules",
  "package.json",
  "tsconfig.*",
  "yarn.lock",
  "*.js",
]
license = "MIT"
name = "voxelize"
version = "0.1.0"

[lib]
name = "voxelize"
path = "server/lib.rs"

[[example]]
name = "demo"
path = "examples/server/main.rs"

[dependencies]
actix-web = "4"
