[package]
description = "A fast multiplayer voxel engine."
edition = "2021"
exclude = [
  "client",
  "dist",
  "examples",
  "node_modules",
  "package.json",
  "tsconfig.*",
  "yarn.lock",
  "*.js",
]
license = "MIT"
name = "voxelize"
version = "0.1.0"

[lib]
name = "voxelize"
path = "server/lib.rs"

[[example]]
name = "demo"
path = "examples/server/main.rs"

[dependencies]
actix = "0.13.0"
actix-broker = "0.4.2"
actix-web = "4"
actix-web-actors = "4.1.0"
ctrlc = "3.2.1"
game-loop = "0.8.2"
hashbrown = "0.12.0"
libflate = "1.2.0"
nanoid = "0.4.0"
num = "0.4.0"
prost = "0.10.0"
serde = {version = "1.0.136", features = ["derive"]}

chrono = "0.4.19"
env_logger = "0.9"
fern = {version = "0.6.0", features = ["colored"]}
log = "0.4.16"
rand = "0.8"

[build-dependencies]
prost-build = "0.10.0"
